### ISSUE TITLE
RFC: What's the plan with the monies?

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/rfcs#12]
ReactiveUI potentially will raise close to $10,000USD this year through the generosity of our backers and corporate sponsors. This is amazing.  Thank-you

https://github.com/reactiveui/reactiveui#backers

@glennawatson raised the question in Slack as to "what's thje plan with the money". My thoughts have been recorded over at https://twitter.com/GeoffreyHuntley/status/1026413749819691009 within the first 10 minutes where "pateron vs open-collective" are detailed.

Our opencollective page includes a high-level overview on how I originally envisioned how the money would be used but we haven't progressed into implementation plans. It's time.

The TL;DR is: Money should be used to improve developer accessibility of ReactiveUI - some ideas:

- Buying people @kentcb's book people are interested in helping (and actually do) improve our documentation.
- Hiring a designer to rebuild our website and create a branding style guide/design guidelines
- Hiring professional documentation authors (http://www.writethedocs.org/) to author the content
- Hiring professional documentation authors (http://www.writethedocs.org/) to edit content writing by others.

Let's keep discussions away from "if we pay maintainers/developers" at this stage because it's too premature. It's time to start delivering on promises to our financial supporters.

/cc
@reactiveui/learning-team 
@reactiveui/core-team 
@reactiveui/community

**Comment by worldbeater** [comment]
+1 for improving the design. It'd be great if ReactiveUI landing page could look like this one < href="https://www.microsoft.com/net">dot.net</a>. But we should be careful and decline <a href="https://forums.fsharp.org/t/website-re-design-we-need-your-input/344/2">bad designs</a>.

**Comment by glennawatson** [comment]
Closing this as https://github.com/reactiveui/rfcs/blob/master/reactiveui/0003-documentation-opencollective.md -- further requests are a new RFC.
