### ISSUE TITLE
RFC: Remove ReactiveCommand abstract base class

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/rfcs#19]
At the moment we have a abstract base class ReactiveCommand (without generics).

I propose we move all the explicit ICommand stuff into ReactiveCommand<TIn, TOut> and remove the ReactiveCommand abstract class. 

This is because users are having binding issues with the abstract version of ReactiveCommand and our current thing we tell users is not to use the abstract ReactiveCommand class.

**Comment by worldbeater** [comment]
Absolutely worth it.

**Comment by glennawatson** [comment]
This was implemented as part of https://github.com/reactiveui/ReactiveUI/pull/1836
