### ISSUE TITLE
RFC: Order more stickers via OpenCollective

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/rfcs#25]
Not much discussion is needed. I'm opening this for transparency sake. I have a bunch of stickers from #mvpsummit and but cannot find them at the moment. When I find them then I'll ship em down to @glennawatson.

Anyway, I heard that we didn't have stickers at XDS.

So hey @RLittlesII I can share with you via LastPass my StickerMule account and then you can reorder the stickers. The last order was 1000 stickers which cost about $214 USD. Once you have the invoice please submit the expense claim. 

Are you okay with also sending em out to folks? Like big packs to meetup organizers and to contributors? You can expense the postage costs. I can share the data behind https://reactiveui.net/stickers with you.

![image](https://user-images.githubusercontent.com/127353/62268941-dab4d180-b474-11e9-8f5e-c8b886d25f06.png)

**Comment by RLittlesII** [comment]
@ghuntley Just seeing this.  I will get this ordered soon, I have a sticker mule account I can do it through.  What I need is the mechanism you are using to send out, I believe it was a google spread sheet.  I am perfectly fine sending them out to folks.

**Comment by glennawatson** [comment]
@RLittlesII has done the ordering of these stickers.
