### ISSUE TITLE
RFC: [Xamarin Forms] When should we adopt Xamarin Forms v3.0.0 as minver?

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/rfcs#7]
We have never really had any documented strategy as to when the version of Xamarin.Forms used by ReactiveUI should be bumped.  Folks of @reactiveui/xamarin-forms-team can you please come together and work out:

* [ ] What our policy is? When do we update minver for `Reactiveui.XamForms` and `ReactiveUI.Events.XamForms`
* [ ] Update https://reactiveui.net/docs/guidelines/platform/xamarin-forms with guidance for consumers of what we support
* [ ] Create https://reactiveui.net/contribute/maintainers/platform-knowledge/xamarin-forms/ with instructions for maintainers how/when to adjust these numbers

https://github.com/reactiveui/ReactiveUI/pull/1631 is ready to merge - the question is when?

**Comment by nhwilly** [comment]
I don't have any existing projects, so now would be okay. :)

**Comment by vatsalyagoel** [comment]
We don't want to be releasing a new version everytime Xamarin updates forms Maj.min.ver.[build] for eg 3.0.0.446417 to 3.0.0.482510 however we do want to update when the min/ver changes. Major version changes should be discussed based on adoption via RFCs like this one. This may cause issues with EventBuilder https://github.com/reactiveui/ReactiveUI/blob/6f616858ab79ba69ccf74d8d4a7acb52f7cb1c8c/src/EventBuilder/Platforms/XamForms.cs#L42 which is using the latest version. Do we also make a decision to pin the nuget package in EventBuilder

**Comment by vatsalyagoel** [comment]
Xamarin is about to release forms 3.1. I think this is the right time to update to 3.0 as minver. Then we can be on track with updating to 3.1 when the time comes. Looking at Nuget it also looks like 3.0 has gained adoption with > 120,000  people downloading Forms 3.0. 2.5 still has higher adoption but we have had a few releases of 8.0 which still supports 2.5

**Comment by RLittlesII** [comment]
I think now is a good time.

As for Policy I would argue we shouldn't move the minver we target until a release candidate is cut for the next version of Xamarin.  This will allow them to work out any bugs, and for some level of stability so we aren't bumping versions every time they fix a bug.

**Comment by glennawatson** [comment]
The minver was changed in https://github.com/reactiveui/ReactiveUI/pull/1631
